engines:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR1,PSR2"
  phpmd:
    enabled: true

ratings:
  paths:
  - src/**
  - bin/**
exclude_paths:
  - tests/**/*
