services:
    ctf.console:
        class:      Llaumgui\CheckToolsFramework\Console\Application
        arguments:  ["%check_tools_framework.name%", "%check_tools_framework.version%"]
        calls:
            - [setContainer, ["@service_container"]]

    ctf.cli:
        class:      Llaumgui\CheckToolsFramework\Cli
        arguments:  ["@ctf.console"]


    # bom
    ctf.checktool.bom:
        class:      Llaumgui\CheckToolsFramework\CheckTool\BomCheckTool
        arguments:  ["%check_tools_framework.check_tools.bom%"]
    ctf.command.bom:
        class:      Llaumgui\CheckToolsFramework\Command\BomCommand
        arguments:  ["bom", "@ctf.checktool.bom"]
        tags:
            -  { name: phpct.command }

    # from_config_file
    ctf.checktool.from_config_file:
        class:      Llaumgui\CheckToolsFramework\CheckTool\FromConfigFileCheckTool
        arguments:  ["%check_tools_framework.check_tools.from_config_file%"]
    ctf.command.from_config_file:
        class:      Llaumgui\CheckToolsFramework\Command\FromConfigFileCommand
        arguments:  ["from_config_file", "@ctf.checktool.from_config_file"]
        tags:
            -  { name: phpct.command }

    # json
    ctf.checktool.json:
        class:      Llaumgui\CheckToolsFramework\CheckTool\JsonCheckTool
        arguments:  ["%check_tools_framework.check_tools.json%"]
    ctf.command.json:
        class:      Llaumgui\CheckToolsFramework\Command\JsonCommand
        arguments:  ["json", "@ctf.checktool.json"]
        tags:
            -  { name: phpct.command }

    # yaml
    ctf.checktool.yaml:
        class:      Llaumgui\CheckToolsFramework\CheckTool\YamlCheckTool
        arguments:  ["%check_tools_framework.check_tools.yaml%"]
    ctf.command.yaml:
        class:      Llaumgui\CheckToolsFramework\Command\YamlCommand
        arguments:  ["yaml", "@ctf.checktool.yaml"]
        tags:
            -  { name: phpct.command }
