parameters:
    service.ctf_console.class:          'Llaumgui\CheckToolsFramework\Console\Application'
    service.ctf_cli.class:              'Llaumgui\CheckToolsFramework\Cli'
    service.ctf_checktool_bom.class:    'Llaumgui\CheckToolsFramework\CheckTool\BomCheckTool'
    service.ctf_checktool_json.class:   'Llaumgui\CheckToolsFramework\CheckTool\JsonCheckTool'


services:
    ctf.console:
        class:      "%service.ctf_console.class%"
        arguments:  ["%check_tools_framework.name%", "%check_tools_framework.version%"]
        calls:
             - [setContainer,   ["@service_container"]]

    ctf.cli:
        class:      "%service.ctf_cli.class%"
        arguments:  ["@ctf.console", "%check_tools_framework.default_commands%"]

    ctf.checktool_bom:
        class:      "%service.ctf_checktool_bom.class%"

    ctf.checktool_json:
        class:      "%service.ctf_checktool_json.class%"
